<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<LangVersion>14.0</LangVersion>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="UnitTest\AggregateTest.cs" />
	  <Compile Remove="UnitTest\ArchiveTest.cs" />
	  <Compile Remove="UnitTest\ComputedTest.cs" />
	  <Compile Remove="UnitTest\TakeTest.cs" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="..\..\scripts\testdata-sqlserver.sql" Link="TestData\datatest-sqlserver.sql" CopyToOutputDirectory="PreserveNewest" />
	  <None Include="..\..\scripts\testdata-sqlite.sql" Link="TestData\datatest-sqlite.sql" CopyToOutputDirectory="PreserveNewest" />
	  <None Include="..\..\scripts\testdata-postgres.sql" Link="TestData\datatest-postgres.sql" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
		<PackageReference Include="NUnit" Version="5.0.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
		<PackageReference Include="coverlet.collector" Version="10.1.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.31" Condition="'$(TargetFramework)' == 'net8.0'" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.20" Condition="'$(TargetFramework)' == 'net9.0'" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" Condition="'$(TargetFramework)' == 'net10.0'" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Namh.Data.DynamicSql\Namh.Data.DynamicSql.csproj" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.1" />
		<PackageReference Include="Npgsql" Version="9.0.4" />
	</ItemGroup>


</Project>
